apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    application: sample-app
    template: eap64-flyway-s2i
    xpaas: 1.1.0
  name: sample-app
spec:
  replicas: 1
  selector:
    deploymentConfig: sample-app
  strategy:
    resources: {}
    type: Rolling
    rollingParams:
      pre:
        failurePolicy: fail
        execNewPod:
          containerName: sample-app
          command:
          - flyway
          - migrate
          - "-user=$ORACLE_USERNAME"
          - "-password=$ORACLE_PASSWORD"
          - "-schema=$ORACLE_DATABASE"
          - "-target=$OPENSHIFT_BUILD_COMMIT"
          volumes:
          - git 
  template:
    metadata:
      creationTimestamp: null
      labels:
        application: sample-app
        deploymentConfig: sample-app
      name: sample-app
    spec:
      containers:
      - env:
        - name: OPENSHIFT_KUBE_PING_LABELS
          value: application=sample-app
        - name: OPENSHIFT_KUBE_PING_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: TX_DATABASE_PREFIX_MAPPING
          value: sample-oracle=ORACLE
        - name: DB_SERVICE_PREFIX_MAPPING
          value: sample-oracle=ORACLE
        - name: ORACLE_USERNAME
          value: schemauser
        - name: ORACLE_PASSWORD
          value: password
        - name: ORACLE_MIN_POOL_SIZE
          value: "1"
        - name: ORACLE_MAX_POOL_SIZE
          value: "10"
        - name: ORACLE_TX_ISOLATION
          value: "false"
        - name: ORACLE_DATABASE
          value: schemaname
        - name: HORNETQ_CLUSTER_PASSWORD
          value: U2DKiXkm
        - name: HORNETQ_QUEUES
        - name: HORNETQ_TOPICS
        image: 172.30.150.84:5000/jboss/flyway:latest
        imagePullPolicy: Always
        name: sample-app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8888
          name: ping
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /opt/eap/bin/readinessProbe.sh
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - name: flyway-base
          mountPath: /var/git
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - name: flyway-base
        gitRepo:
          repository: "https://github.com/sterburg/jboss-flyway.git"
          revision: master
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - sample-app
      from:
        kind: ImageStreamTag
        name: sample-app:latest
    type: ImageChange
  - type: ConfigChange
status: {}
